Bavid-Dowie/Iterator

- client/src/App.js
- client/src/components/CreateArticle.js
Created basic form for creating a new article.
> Add static content in CreateArticle

- scripts/resetDb.js
> reset script written

- client/src/App.js
- client/src/components/UpdateArticle.js
Add basic form to update article.
> Add static content to UpdateArticle component

- client/src/App.js
- client/src/components/Homepage.js
Add title, app description, login form, and sign up form for homepage.
> Build out static homepage content

- models.js
- package.json
- scripts/seedDb.js
- server.js
Set up server to run on port 3001
> Server running

- models.js
- package.json
- server.js
Troubleshooting the inability to reset database on heroku bash
> Heroku troubleshooting

- client/src/components/UpdateUser.js
add component for user to update/edit their profile
> add Update User component

- models.js
- package.json
- server.js
> Server routing

- package.json
- server.js
All server routes made and ready for testing
> Server routes ready for testing

- server.js
> userId route

- client/src/App.js
- client/src/components/UserProfile.js
> React routes made

- client/src/App.js
- client/src/components/Homepage.js
- client/src/components/UserProfile.js
- server.js
Changed a few functions in app, homepage, and userprofile in order to dynamically render the "logged in" user's information on the profile page.  May be a bit hacky, but we can review later
> Some Fake Auth functionality added

- client/src/components/CreateArticle.js
Minor changes made to CreateArticle.js.
> Update to CreateArticle

- client/src/components/CreateArticle.js
> Fixed Author Input

- client/src/components/UserArticles.js
- client/src/components/UserProfile.js
Still trying to render user articles
> Lm articles component function

- client/src/App.js
- client/src/components/Homepage.js
- client/src/components/UserProfile.js
> Lm local storage

- client/src/components/AllArticles.js
A page with all articles exists
> all articles route added

- client/src/components/AllArticles.js
Deleted dead functions from when we were thinking of doing auth
> Cleaning up unused code

- client/src/components/CreateArticle.js
- client/src/components/UserProfile.js
The syntax for the create article function has been changed to reflect local storage changes yesterday
> create article changed

- client/src/App.js
- client/src/components/Homepage.js
- client/src/components/UserProfile.js
- scripts/seedDb.js
State of loggedin flips on componentDidMount on UserProfile in order to enable the user to logout it also added Maddy's seed files
> Fixed the logout button to work under all conditions

- client/src/App.js
- client/src/components/AllArticles.js
Changed the keys for the divs rendered for all articles from math.random to the individual article key and deleted the get random numbers function in the all articles component
> Tweaked the keys on all articles

- client/src/App.js
- client/src/components/AllArticles.js
- client/src/components/Article.js
- client/src/components/UpdateArticle.js
Form now only renders when the article's userId matches the id of the logged in user
> Place conditional rendering on update article form

- client/src/App.css
Articles banner width should now be set to 100vw.
> fix banner articles banner width

- client/src/App.js
- client/src/components/AllArticles.js
- client/src/components/Article.js
- client/src/components/CreateArticle.js
- client/src/components/UserProfile.js
- server.js
Fixed all the bugs causing the site to not work on refresh
> Sm bug fixes

- client/src/components/AllArticles.js
- client/src/components/Article.js
Fixed the bug with redirects causing users to not be able to get to the articles page after log in/register by moving the creation of the token variable inside the render of the components
> Redirect bug fixed
